services:

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    command: ["mariadbd", "--event-scheduler=ON"]
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Paris
    volumes:
      - vol_BDD:/var/lib/mysql
    networks:
      - marais_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb
    networks:
      - marais_net

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - vol_grafana:/var/lib/grafana
    networks:
      - marais_net


  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"       # MQTT standard
      - "8883:8883"       # MQTT TLS
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    networks:
      - marais_net

  app_python:
    build:
      context: ./app_python
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      MQTT_BROKER: ${MQTT_BROKER}
      MYSQL_MQTT_HOST: ${MYSQL_MQTT_HOST}
      MYSQL_MQTT_USER: ${MYSQL_MQTT_USER}
      MYSQL_MQTT_PASSWORD: ${MYSQL_MQTT_PASSWORD}
      MYSQL_MQTT_DATABASE: ${MYSQL_MQTT_DATABASE}
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    depends_on:
      - mariadb
      - mosquitto
    networks:
      - marais_net

volumes:
  vol_BDD:
  vol_grafana:
  mosquitto_data:
  mosquitto_log:

networks:
  marais_net:
    driver: bridge
