persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Fichier de mots de passe
password_file /mosquitto/config/passwd

# Listener MQTT TLS (chiffré) - port 8883
listener 8883
certfile /mosquitto/config/server.crt
keyfile /mosquitto/config/server.key
cafile /mosquitto/config/ca.crt
allow_anonymous false
