persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Listener MQTT standard (temporaire pour test)

# Listener MQTT TLS (chiffré)
listener 8883
certfile /mosquitto/config/server.crt
keyfile /mosquitto/config/server.key
cafile /mosquitto/config/ca.crt
allow_anonymous false


# Fichier de mots de passe
password_file /mosquitto/config/passwd
