services:

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    command: ["mariadbd", "--event-scheduler=ON"]
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: Marais_R_Site
      MARIADB_USER: Marais_R_Site_User
      MARIADB_PASSWORD: Marais_R_Site_User_123
    volumes:
      - vol_BDD:/var/lib/mysql
    networks:
      - marais_net

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config:ro
    networks:
      - marais_net

  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      MYSQL_DATABASE: ${MYSQL_WEB_DATABASE}
      MYSQL_USER: ${MYSQL_WEB_USER}
      MYSQL_PASSWORD: ${MYSQL_WEB_PASSWORD}
      MYSQL_HOST: ${MYSQL_WEB_HOST}
    depends_on:
      - mariadb
    networks:
      - marais_net


  app_python:
    build:
      context: ./app_python
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
    env_file:
      - .env
    depends_on:
      - mariadb
      - mosquitto
    networks:
      - marais_net

volumes:
  vol_BDD:
  mosquitto_data:
  mosquitto_log:

networks:
  marais_net:
    driver: bridge