api:
  dashboard: true
  insecure: true

entryPoints:
  websecure:
    address: ":443"
  mqtts:
    address: ":8883"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: eleve.marais@btssn.fr
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO

accessLog:
  format: common

ping:
  entryPoint: "websecure"


