http:
  routers:
    phpmyadmin:
      rule: "Host(`marais2026.btssn.ovh`) && PathPrefix(`/phpmyadmin`)"
      entryPoints:
        - websecure
      service: phpmyadmin-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - phpmyadmin-stripprefix
      priority: 100

  middlewares:
    phpmyadmin-stripprefix:
      stripPrefix:
        prefixes:
          - "/phpmyadmin"

  services:
    phpmyadmin-service:
      loadBalancer:
        servers:
          - url: "http://phpmyadmin:80"
