http:
  routers:
    grafana:
      rule: "Host(`marais2026.btssn.ovh`) && PathPrefix(`/grafana`)"
      entryPoints:
        - websecure
      service: grafana-service
      tls:
        certResolver: letsencrypt
      priority: 100

  services:
    grafana-service:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
